### PR TITLE
fix: 修复 b站 和 youtube 解析阻塞主进程的问题，修复其他若干问题

### PR DESCRIPTION
**Pull request by fllesser**
commit 231c4a63dfb14a8d4e744134377353bfc9167940
Author: fllesser <fllesive@gmail.com>
Date:   Tue Nov 26 15:47:55 2024 +0800

    build(deps): update .gitignore and pyproject.toml

commit be8ed41c6993d68228dc871930f249ef2f1f8ee2
Author: FLLess <64878354+fllesser@users.noreply.github.com>
Date:   Tue Nov 26 10:18:25 2024 +0800

    update nonebot-plugin-resolver/core/ytdlp.py

commit b68cc26fe3cb699aa00e5de440df4cd94ecce286
Author: FLLess <64878354+fllesser@users.noreply.github.com>
Date:   Tue Nov 26 07:46:33 2024 +0800

    chore: 调整 yt-dlp format 以兼容竖屏

commit 1aab180df3ffce719531dafdca0058c90df72bdd
Author: FLLess <64878354+fllesser@users.noreply.github.com>
Date:   Tue Nov 26 06:51:11 2024 +0800

    fix: 修复 tiktok 因为分辨率解析失败

commit cee7a1ec6637567e2e97d870c46da7f2e3bb939f
Author: FLLess <64878354+fllesser@users.noreply.github.com>
Date:   Tue Nov 26 06:42:44 2024 +0800

    update pyproject.toml

commit 93bb8ea91237502ff0544430204fecaa285efa31
Author: FLLess <64878354+fllesser@users.noreply.github.com>
Date:   Tue Nov 26 06:34:26 2024 +0800

    update README.md

commit 3c595d0f6d5ef1d29f3c33d35d82bc914b079727
Author: FLLess <64878354+fllesser@users.noreply.github.com>
Date:   Tue Nov 26 06:13:57 2024 +0800

    remove: 移除b站解析合并视频旧代码

commit 3858323d293d60429aae621dee3c8d3d6c34c03d
Author: FLLess <64878354+fllesser@users.noreply.github.com>
Date:   Tue Nov 26 06:12:32 2024 +0800

    update nonebot-plugin-resolver/__init__.py

commit 5594eb65e130a1928d1bc3e23a6e1c0ed8b68cfe
Author: FLLess <64878354+fllesser@users.noreply.github.com>
Date:   Tue Nov 26 06:01:56 2024 +0800

    fix:.尝试修复b站解析阻塞问题

commit 2f76f19f735223449e25d5817c5f996103e14df1
Author: FLLess <64878354+fllesser@users.noreply.github.com>
Date:   Tue Nov 26 06:01:43 2024 +0800

    fix:.尝试修复b站解析阻塞问题

commit d3ef81da406c30f98adc803dec421574512604a7
Author: FLLess <64878354+fllesser@users.noreply.github.com>
Date:   Tue Nov 26 05:57:33 2024 +0800

    chore: yt-dlp 下载视频统一分辨率为1280x720

commit 359987a5edaf171d58dcd963880647b69a82a8c4
Author: FLLess <64878354+fllesser@users.noreply.github.com>
Date:   Tue Nov 26 05:55:34 2024 +0800

    update nonebot-plugin-resolver/__init__.py

commit 9cc2e990428f4198f5b21b57c31288423456e61a
Author: FLLess <64878354+fllesser@users.noreply.github.com>
Date:   Tue Nov 26 05:16:26 2024 +0800

    remove: 移除 ytdlp 旧代码

commit 80e6b5e9353368eefd1865ba987e85a7a42a961c
Author: FLLess <64878354+fllesser@users.noreply.github.com>
Date:   Tue Nov 26 05:07:31 2024 +0800

    update nonebot-plugin-resolver/__init__.py

commit 622f9af0734ade8fa3e93410491d1a2712766a0e
Author: FLLess <64878354+fllesser@users.noreply.github.com>
Date:   Tue Nov 26 05:01:27 2024 +0800

    update nonebot-plugin-resolver/__init__.py

commit a2bd5298cc37588fb4940311f235eb640ed31438
Author: FLLess <64878354+fllesser@users.noreply.github.com>
Date:   Tue Nov 26 04:58:28 2024 +0800

    refactor: yt-dlp 调用 重写为异步

commit de1951b64af1bd8c883475c82ad193ef1d45597a
Author: FLLess <64878354+fllesser@users.noreply.github.com>
Date:   Tue Nov 26 04:07:42 2024 +0800

    chroe: ytb

commit 8d193015606273cc897f4e4ec08b9882cea40f4c
Author: FLLess <64878354+fllesser@users.noreply.github.com>
Date:   Tue Nov 26 04:06:47 2024 +0800

    update nonebot-plugin-resolver/__init__.py

commit 4ade41858338f3529011b08c66c92d44308e9575
Author: FLLess <64878354+fllesser@users.noreply.github.com>
Date:   Tue Nov 26 04:00:10 2024 +0800

    chore: 推特解析 海外服务器判断

commit 45e56526fedc314718500f981ed6578410bf2297
Author: FLLess <64878354+fllesser@users.noreply.github.com>
Date:   Fri Nov 22 23:29:58 2024 +0800

    chore: 校准bilibili解析正则

### CODE REVIEW

**Comment by zhiyu1998** [comment]
测试过没有？如何测试阻塞的？

**Comment by fllesser** [comment]
> 测试过没有？如何测试阻塞的？

测试过了啊，你之前ytb用的subprocess.run，这个是会阻塞主进程的，下载视频的时候，nonebot都收不到别的消息

**Comment by fllesser** [comment]
编程我比较业余，哪里写的不对的不要见怪哈🐯

**Comment by zhiyu1998** [comment]
OK 感谢PR

**Pull request merged**
